import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../app/routes/app_routes.dart';
import '../../assets/oppose_assets.dart';
import '../../components/buttons/oppose_buttons.dart';
import '../../components/core/paper_card.dart';
import '../../components/core/status_pill.dart';
import '../../components/layout/oppose_header.dart';
import '../../components/layout/oppose_screen.dart';
import '../../components/stickers/sticker_image.dart';
import '../../state/mock_data/mock_oppose_data.dart';
import '../../theme/oppose_spacing.dart';
import '../../types/domain_models.dart';

class RoomSummaryScreen extends StatelessWidget {
  const RoomSummaryScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final summary = MockOpposeData.summary;

    return OpposeScreen(
      showBottomNavigation: true,
      children: [
        OpposeHeader(
          title: 'Room Summary',
          subtitle: '${summary.title} - ${summary.durationLabel}',
          trailing: const AIStatusPill(status: AIStatusValue.summarizing),
        ),
        const SizedBox(height: OpposeSpacing.xl),
        const Center(
          child: StickerImage(asset: OpposeAssets.roomSummaryBima, size: 120),
        ),
        const SizedBox(height: OpposeSpacing.lg),
        const StatusPill(
          label: 'Generated by AI from allowed room context',
          icon: Icons.verified_rounded,
        ),
        const SizedBox(height: OpposeSpacing.xl),
        _SummarySection(title: 'Main takeaways', items: summary.takeaways),
        _SummarySection(title: 'Best arguments', items: summary.bestArguments),
        _SummarySection(title: 'Funny moments', items: summary.funnyMoments),
        _SummarySection(title: 'Open questions', items: summary.openQuestions),
        PaperCard(
          child: ListTile(
            contentPadding: EdgeInsets.zero,
            leading: const Icon(Icons.lock_outline_rounded),
            title: Text(summary.visibility),
            subtitle: const Text(
              'You control save, share, and delete actions.',
            ),
          ),
        ),
        const SizedBox(height: OpposeSpacing.xl),
        PrimaryButton(label: 'Save', onPressed: () {}),
        const SizedBox(height: OpposeSpacing.md),
        SecondaryButton(label: 'Share with room', onPressed: () {}),
        const SizedBox(height: OpposeSpacing.md),
        DangerButton(
          label: 'Delete summary',
          onPressed: () => context.go(AppRoutes.home),
        ),
      ],
    );
  }
}

class _SummarySection extends StatelessWidget {
  const _SummarySection({required this.title, required this.items});

  final String title;
  final List<String> items;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: OpposeSpacing.md),
      child: PaperCard(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: OpposeSpacing.sm),
            for (final item in items) Text('- $item'),
          ],
        ),
      ),
    );
  }
}
